### ISSUE TITLE
Implement some real CI

### ISSUE THREAD

**Issue by ghuysmans** [ghuysmans/sqldep#12]

**Comment by mohitsaxenaknoldus** [comment]
I can do it if you tell me how you build or test this project.

**Comment by ghuysmans** [comment]
Hi,
First, thank you for your interest!
At the moment, there's nothing to compile: I only got the naive version to work; [the ocaml branch](https://github.com/ghuysmans/sqldep/tree/ocaml) should be more robust, but the underlying library isn't complete enough (yet?). Scripts are easier to run once you've installed them using `make install`. You may specify a `PREFIX` to tell it where it should install them.
Tests aren't completely trivial (but probably quite unpleasant in _sh_), because multiple results are equivalent: `TABLE t: t2 t3` is the same as `TABLE t: t3 t2` and `TABLE t: t3 t2 t2`, and it may appear anywhere in the output.

**Comment by mohitsaxenaknoldus** [comment]
1) I see there is already a workflow present. What does it do? 
2) Do first you do `make install` and then run the tests?

**Comment by ghuysmans** [comment]
The _access_ job in the workflow ran [`dump_access_views.vbs`](https://github.com/ghuysmans/sqldep/blob/master/utils/dump_access_views.vbs). This script extracts views from an Access database; by the way, that was my first real-world use case, and I used even simpler regular expressions in VBA at that time.

**Comment by ghuysmans** [comment]
[`utils/dep_to_schema_dot.sh`](../blob/master/utils/dep_to_schema_dot.sh) is the script that actually needs another one to be installed, and its output is really gross, so you don't absolutely have to install them to test `sqldep` itself.

**Comment by ghuysmans** [comment]
[`tests/test.sh`](../blob/master/tests/test.sh) still tries to run the OCaml version, then it compares the list of views with those we expect `sqldep` to find. It might be rewritten as a Makefile with pattern rules.

**Comment by mohitsaxenaknoldus** [comment]
This is getting confusing. So, if i run `utils/dep_to_schema_dot.sh`, it will test the `sqldep` right?

**Comment by ghuysmans** [comment]
`utils/dep_to_schema_dot.sh` takes dependencies and produces a dot script with schema dependencies instead of object (tables & views) dependencies. It helps you find circular dependencies between projects.

**Comment by ghuysmans** [comment]
The use cases I thought about are described in the readme, but maybe I was unclear...

**Comment by mohitsaxenaknoldus** [comment]
Ok so how should I proceed with this?

**Comment by ghuysmans** [comment]
In short, my current comparison strategy (`diff`) might be a bit brittle to test `sqldep`, but we can already just issue a `make test` in `tests` on any Ubuntu VM.
The two other tools, `utils/dep_to_dot.sh` and `utils/dep_to_schema_dot.sh`, are supposed to be simpler, so maybe we don't have to test them.

**Comment by ghuysmans** [comment]
To further reduce the confusion, I should probably use consistent script names, i.e. avoid things like this: https://github.com/ghuysmans/sqldep/blob/ba91878a9dbe5c519bc910d18bb3278bdb85d60e/Makefile#L8

**Comment by mohitsaxenaknoldus** [comment]
Running `make test` inside `tests/` give me: `make: *** No rule to make target 'test'.  Stop.`

**Comment by ghuysmans** [comment]
Oops, I did something wrong: I typed _all_ instead of _test_ in `tests/Makefile`.

**Comment by mohitsaxenaknoldus** [comment]
PR: https://github.com/ghuysmans/sqldep/pull/15
