### ISSUE TITLE
Pre-commit check

### ISSUE THREAD

**Issue by ghuysmans** [ghuysmans/sqldep#9]
- [ ] Integrate #1

**Comment by ghuysmans** [comment]
- [ ] Detect tables you can't drop because of FOREIGN KEYs

**Comment by ghuysmans** [comment]
Blocked by #6

**Comment by mohitsaxenaknoldus** [comment]
So we need two pre-commit checks one to detect tables that can't be dropped due to FK's and another to detect the breaking views? I don't know much `sql` commands to run these checks so you'll need to help with those but I can do the `git` part for sure!

**Comment by ghuysmans** [comment]
I've fixed my first comment, it was poorly thought out. I'd like to detect statically those errors (so there's no need for extra SQL). It depends heavily on the order of the references, and it is fortunately preserved in the dependencies we produce. So we could process our output and report any undefined reference, what do you think?

**Comment by mohitsaxenaknoldus** [comment]
Yeah, that can work. The pre-commit hook can build the project and produce those dependencies which we can further process to find what we looking for. What format are those dependencies and output in?

**Comment by ghuysmans** [comment]
The dependencies look like this:
```
TABLE print.paper:
TABLE print.service: print.paper
VIEW print.per_user: print.service print.paper
VIEW print.per_class: print.service print.paper school.class
```

The schema name is optional, so you might also read this:
```
TABLE paper:
TABLE service: paper
VIEW per_user: service paper
VIEW per_class: service paper school.class
```

I haven't decided on an output format yet. Maybe error messages similar to compilers' output, like this?
```
4: undefined object 'school.class'
```

**Comment by mohitsaxenaknoldus** [comment]
Ok, so how will we evaluate this result?

**Comment by ghuysmans** [comment]
In the hook? The checker will return a non-zero exit code.

**Comment by ghuysmans** [comment]
We should should complain about FKs that refer to views.

**Comment by ghuysmans** [comment]
The upcoming implementation will be harder to test...
